apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-hamza-cheznouslabas-fr-tls
  namespace: monitoring # Replace with the namespace where your application is deployed
spec:
  secretName: prometheus-hamza-tls-secret  # The secret where the TLS certificate will be stored
  issuerRef:
    name: letsencrypt-prod # Reference to the ClusterIssuer
    kind: ClusterIssuer
  commonName: prometheus.hamza.cheznouslabas.fr
  dnsNames:
    - prometheus.hamza.cheznouslabas.fr
  acme:
    config:
      - http01:
          ingressClass: nginx # The ingress class used by the NGINX Ingress Controller
        domain: prometheus.hamza.cheznouslabas.fr # The domain for which the certificate is requested