name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Select the Terraform workspace to use"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3 # Change if needed

      # Step 3: Format check (CI)
      - name: Vérification du formatage Terraform
        run: terraform fmt -check

      # Step 4: Validation (CI)
      - name: Validation Terraform
        run: terraform validate

      # Step 5: Security Scan (CI, optionnel)
      - name: Scan sécurité avec Terrascan
        uses: accurics/terrascan-action@v1

      # Step 6: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Remplace par ta région

      # Step 7: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 8: Select Workspace
      - name: Select Workspace
        run: |
          terraform workspace select ${{ github.event.inputs.workspace }} || terraform workspace new ${{ github.event.inputs.workspace }}

      # Step 9: Terraform plan
      - name: Terraform plan
        run: terraform plan

      # Step 10: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
